name: ipfs_client
description: Basic IPFS client for low-level interactions with an IPFS daemon
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  quiver: ^2.1.3
  path: ^1.7.0
  uri: ^0.11.3+1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
